pipeline:
  test:
    image: python:3.9-slim-buster
    commands:
      - python3 -m unittest discover test -v

  k8_deploy:
    image: ghcr.io/bh90210/dron8s:latest
    settings:
      yaml: ./streamlinkweb-deployment.yaml
      kubeconfig:
        from_secret: kubeconfig

  ecr_build:
    image: plugins/ecr
    environment:
      - ECR_ACCESS_KEY=${aws_access_key}
      - ECR_SECRET_KEY=${aws_secret_key}
    repo: streamlinkweb
    registry: ${aws_ecr_registry_url}
    secrets: [aws_access_key, aws_secret_key, aws_ecr_registry_url]
