pipeline:
  test:
    image: python:3.9-slim-buster
    commands:
      - python3 -m unittest discover test -v

  k8_deploy:
    image: ghcr.io/bh90210/dron8s:latest
    environment:
      - KUBERNETES_SERVICE_HOST=https://43.239.250.43
      - KUBERNETES_SERVICE_PORT=6443
    settings:
      kubeconfig:
        from_secret: kubeconfig
      yaml: ./streamlinkweb-deployment.yaml
    secrets: [kubeconfig, kubernetes_server]

  ecr_build:
    image: plugins/ecr
    environment:
      - ECR_ACCESS_KEY=${aws_access_key}
      - ECR_SECRET_KEY=${aws_secret_key}
    settings:
      repo: streamlinkweb
      registry: ${aws_ecr_registry_url}
    secrets: [aws_access_key, aws_secret_key, aws_ecr_registry_url]
