pipeline:
  test:
    image: python:3.9-slim-buster
    commands:
      - python3 -m unittest discover test -v
  ecr_build:
    image: plugins/ecr
    environment:
      - ECR_ACCESS_KEY=${aws_access_key}
      - ECR_SECRET_KEY=${aws_secret_key}
    secrets: [aws_access_key, aws_secret_key]
    settings:
      repo: streamlinkweb
      registry:
        from_secret: aws_ecr_registry_url
